# Generated by Django 3.2.6 on 2021-09-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegister',
            fields=[
                ('NationalCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('FamilyName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Tele', models.CharField(max_length=8)),
                ('Phone', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('TeacherId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Degree', models.CharField(max_length=100)),
                ('TermContractNumber', models.IntegerField(default=1)),
                ('NationalCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherregister')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('ScoreId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Score', models.IntegerField(default=0)),
                ('VerifyDegree', models.BooleanField()),
                ('LessonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.lesson')),
                ('TeacheId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryReports',
            fields=[
                ('TransactionId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Price', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(verbose_name='Deposit Date')),
                ('Status', models.CharField(max_length=100)),
                ('NationalCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherregister')),
                ('TermId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.term')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ReqId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Lesson', models.CharField(max_length=50)),
                ('TermDate', models.DateTimeField(verbose_name='Term Date you want presentiantion')),
                ('Description', models.CharField(max_length=200)),
                ('TeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo')),
            ],
        ),
    ]
