# Generated by Django 3.2.6 on 2021-09-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_studentscore_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscore',
            name='StudentId',
        ),
    ]
