# Generated by Django 3.2.6 on 2021-09-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryRegister',
            fields=[
                ('NationalCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('FamilyName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Tele', models.CharField(max_length=8)),
                ('Phone', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SecretarySiteRegister',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSiteRegister',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSiteRegister',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('TermId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StartDay', models.DateTimeField(verbose_name='start term day')),
                ('EndDay', models.DateTimeField(verbose_name='end term day')),
                ('DateNumberInWeek', models.IntegerField(default=1)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('LessonId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Studentnumber', models.IntegerField(default=0)),
                ('ClassNumber', models.CharField(max_length=5)),
                ('DateTime', models.DateTimeField(verbose_name='Day and Time start class')),
                ('TermId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.term')),
            ],
        ),
    ]
