# Generated by Django 3.2.6 on 2021-09-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('NationalCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('FamilyName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Tele', models.CharField(max_length=8)),
                ('Phone', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOfTuition',
            fields=[
                ('TransactionId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Price', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(verbose_name='Deposit Date')),
                ('Status', models.CharField(max_length=100)),
                ('NationalCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentregister')),
                ('TermId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary.term')),
            ],
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.IntegerField()),
                ('Nationalcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentregister')),
                ('TransactionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.paymentoftuition')),
            ],
        ),
    ]
