# Generated by Django 3.2.6 on 2021-09-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_studentscore_studentid'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationbackground',
            name='ScoreId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.studentscore'),
            preserve_default=False,
        ),
    ]
