# Generated by Django 3.2.6 on 2021-09-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_educationbackground_scoreid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationbackground',
            name='ScoreId',
        ),
    ]
